### PR TITLE
Add Vectorized images for the Launcher's foreground and background.

### PR DESCRIPTION
**Pull request by Irishsmurf**
This change moves from using `.png` images, and instead utilizes a vector for the foreground image, and a shape containing the background gradient.

Examples below. (After follows Before)

Square_Before
Square_After

---
Before_Square_Colour
Circle_Icon_Colour

---

Before_Square_Mono
Circle_Icon_Monochrome

### CODE REVIEW

**Comment by grishka** [comment]
The original icon is more nuanced than that, the original asset has SVG filters, so I had to rasterize it. It can't be losslessly converted to a vector drawable — I would've done that if it was possible.
https://user-images.githubusercontent.com/1478258/200151067-4722cdb5-3441-436e-805e-6dcc48b9b9fd.svg
Background
Foreground

**Comment by danielcherubini** [comment]
I think you're missing that android 13 themed icons require this.

**Comment by PhaserArray** [comment]
> I think you're missing that android 13 themed icons require this.

Exactly. I would much prefer a simplified adaptive icon that works better with Android 13 over the rasterized version.

**Comment by grishka** [comment]
I already added a themed icon. It is, indeed, fully vector.

**Pull request closed without merging**
