### PR TITLE
Major code style cleanups.

### PR DESCRIPTION
**Pull request by evelynmarie**
This pull request makes some _major_ improvements to the code style of the project's source code.  This PR is huge, but simple - the only things that were done include the following: running <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>L</kbd> across the entire project and all its Java source files to improve spacing and tab spaces and everything else to align with Android Studio's default code style guidelines; using the `final` keyword in most places where its highly suggested (there are more than likely variables I missed, but those can be fixed later on), and other miscellaneous code style changes like using brackets for if/else statements where necessary. 

Several libraries and dependencies were updated as well (per Android Studio recommendations), including the Android Gradle Plugin to version 8.x, meaning that some properties in the project's build.gradle file was changed as well. Several unnecessary dependencies on test libraries were removed as well, since this project does not have any tests.

I have done some pretty extensive testing with these changes on my S22 Ultra, and there were no differences or oddities in behaviour from what I noticed.

### CODE REVIEW

**Comment by grishka** [comment]
Do you really think it's appropriate to come into someone else's project like this and submit a PR that changes every single file without actually meaningfully changing anything? What kind of reaction are you expecting? I'm genuinely curious.

**Comment by evelynmarie** [comment]
> Do you really think it's appropriate to come into someone else's project like this and submit a PR that changes every single file without actually meaningfully changing anything? What kind of reaction are you expecting? I'm genuinely curious.

@grishka I wasn’t expecting this kind of response. The codebase needs a consistent code style. It’s massively inconsistent. It even includes files from AOSP, like various widgets and views, that have a different code style from the rest of the files. I separated the changes into three commits as well, so that way they’d be easier to sift through. I’m not trying to vandalize the project, there’s just no way to viably do this (cleaning up the code style) without touching _every_ source file in the project 🙁

**Comment by evelynmarie** [comment]
My focus of this PR was to try and improve the code style so that way it might encourage future contributors to work on the project, because there are some people who can be put off by an inconsistent code style.

It was never to vandalize or hurt the work you’ve put in. I only ran the reformat code tool in AS and made minor changes by hand after that.

**Comment by evelynmarie** [comment]
Additionally, I wouldn’t have done this at all if I didn’t think it was meaningful. In my mind it is. I was trying to improve the code base’s style, as i’ve mentioned, as it’s never previously been done. People submit these sorts of PRs to projects all the time, they aren’t that significant in scope - in file count it might be, but in actual additions and deletions it’s most definitely not.

Look at the Mastodon iOS project for what i mean by good code style. It follows the Swift style guide, or at least it follows the norm. My focus of this PR was to allow the codebase to follow the Java style guide for Android.

**Comment by grishka** [comment]
> The codebase needs a consistent code style. It’s massively inconsistent.

It is *consistent*, it's just not mainstream.

> there’s just no way to viably do this (cleaning up the code style) without touching every source file in the project 🙁

Do you really think I wouldn't have done it myself if I wanted to do it?

> I only ran the reformat code tool in AS and made minor changes by hand after that.

Yes, I do run it sometimes, except my settings are different. I would never, ever, under no circumstances, want space indents, for example.

I should really add an editorconfig file.

**Comment by evelynmarie** [comment]
> > The codebase needs a consistent code style. It’s massively inconsistent.
> 
> 
> 
> It is *consistent*, it's just not mainstream.
> 
> 
> 
> > there’s just no way to viably do this (cleaning up the code style) without touching every source file in the project 🙁
> 
> 
> 
> Do you really think I wouldn't have done it myself if I wanted to do it?
> 
> 
> 
> > I only ran the reformat code tool in AS and made minor changes by hand after that.
> 
> 
> 
> Yes, I do run it sometimes, except my settings are different. I would never, ever, under no circumstances, want space indents, for example.
> 
> 
> 
> I should really add an editorconfig file.

Except these days spaces are the norm, it’s what most people follow for projects these days.

And there’s still the issue of the fact that there’s a significant lack of spaces in this project when it comes to writing statements. Not separating the equal sign with a space before and after, and not putting space after `if`/`else` is IMHO bad code style that pretty much no projects follow. That’s my main gripe, and it makes the codebase severely hard to understand / parse. I’m not saying this to criticize, as the app works and looks great on the front end. But the codebase needs improvement in the style which is why I submitted this PR.

**Comment by evelynmarie** [comment]
And btw, adding a .editorconfig doesn’t fix the issue that this codebase has an unbearable code style internally. No other Mastodon first party project suffers from this. It’s literally only this one.

**Comment by grishka** [comment]
> Except these days spaces are the norm

It's not like I care about any kind of global norms and what "most people" do. If I did, I would've used Kotlin and everything Jetpack has to offer, the app would've been 50 megabytes and would've taken 10 seconds for a cold launch on a flagship device.

> But the codebase needs improvement in the style which is why I submitted this PR.

Again, if I did want this, I'd have done it myself. I haven't done it.

> And btw, adding a .editorconfig doesn’t fix the issue that this codebase has an unbearable code style internally.

It stops people attempting to reformat everything and makes the code they add follow the project style. If you don't like this code style, you're free to make a fork. But please don't try to force **me** to change my ways. This is just rude.

**Comment by evelynmarie** [comment]
> It's not like I care about any kind of global norms and what "most people" do. If I did, I would've used Kotlin and everything Jetpack has to offer, the app would've been 50 megabytes and would've taken 10 seconds for a cold launch on a flagship device.

@grishka The whole "10 second launch on a flagship device" claim is false. Look at Tusky, a Mastodon third party client on Android. It launches in around the same time the first party client does, and has more features (but a subjectively worse design IMHO as its stuck in the Material Design 1.x days), and is written in Kotlin. And it's def. not 50 MB. It's 20 MB in its debug state, 15 MB in its release state and it uses the full AndroidX libraries instead of trimmed down ones. Yeah, its not as small as the first party client, but on flagship phones, app size doesn't really matter as much anymore. But I never crticized the fact that this app uses Java instead of Kotlin, as language preference doesn't matter. Both languages are good, and Java is finally getting better on Android too, esp. with Android 14 and its adoption of Java 17 on a system level. 

I just _personally_ disagree with the code style you've decided to adopt for this project. It is, subjectively, unclean. My _only_ gripe is the lack of spaces between things like statements, e.g. the following for statements and if/else blocks:
```java
// current style for statements
String beans="yum";
// nicer style (imo)
String beans = "yum";
// current style for if statements
if(personSaysHello)
    System.out.printLn("Hello!");
// nicer style for if statements (imo)
if (sayHello) {
    System.out.printLn("Hello!");
}
```
Those are the biggest gripes I have - that's what makes this codebase appear unclean. It is entirely your project, I am fully aware of that. But don't you think that if spaces were introduced for at least statements and if/else blocks, it would make the codebase look a lot nicer? 

This is one of the _only_ projects I am aware of that has this code style.

**Pull request closed without merging**
