### PR TITLE
Fixed Japanese locale mistake "n minutes ago"

### PR DESCRIPTION
**Pull request by kgtkr**
nヶ月前: n months ago
n分前: n minutes ago

### CODE REVIEW

**Comment by grishka** [comment]
Translations are done on Crowdin.
https://crowdin.com/project/mastodon-for-android

**Comment by kgtkr** [comment]
OK

**Comment by grishka** [comment]
(it's actually already correct there)
image

**Comment by kgtkr** [comment]
It was my lack of confirmation. Thank you for teaching me

**Pull request closed without merging**
