### PR TITLE
Add "Unlisted" visibility option for posts

### LINKED ISSUE #37: Add "Unlisted" option for toots.
Web Mastodon supports that feature, but in this app I cannot use it. In this app I can only use _public_, _Followers only_, _Only people I mention_.

### PR DESCRIPTION
**Pull request by sk22**
Fixes #37

### CODE REVIEW

**Comment by Gargron** [comment]
This option has been omitted on purpose since it overlaps with public in almost all ways. We keep the dropdown simple, with all other options being very intuitive to understand.

**Comment by afheisleycook** [comment]
gargon you dont listne your users @Gargron you should revoke as creator and replaced

**Comment by mxamber** [comment]
> it overlaps with public in almost all ways

...hardly true? Having public posts that can be boosted and shared around but aren't visibly to any, pardon my French, any random jerk browsing public/fed for users to harrass, is vital to anyone who's worried about this sorta thing. Which isn't that few people.

**Comment by afheisleycook** [comment]
step down some one who  cna do better job @Gargron

**Comment by afheisleycook** [comment]
you dont deserver to work on mastadon

**Comment by sk22** [comment]
I agree that it gets more complicated with the "Unlisted" option being available (as new users might not understand what this even means) – but it's also an essential part of Mastodon, if you ask me.

I suspect that users coming from Twitter would rather expect Unlisted-like behavior as there's no public timelines on Twitter. And since the Community timeline isn't displayed prominently either, chances are new users don't even realize it exists – possibly exposing them to trolls who find posts on public timelines.

In my opinion, users should at least have the option to post unlisted, as

1. it's a feature Mastodon (thankfully) supports
3. it makes sense for the way the Android app endorses people to use Mastodon (considering the Community timeline is quite hidden in the app and the Federated timeline doesn't even exist)
4. is something that can increase users' safety.

**Comment by n0toose** [comment]
> any random jerk browsing public/fed for users to harrass, is vital to anyone who's worried about this sorta thing. Which isn't that few people.

Ignoring the flat out embarrassing conduct of a specific person here, I can attest to the fact that I have seen waves of people going out of their way to use the federated timeline to harass minorities. The thing I like about Mastodon is that it's not an "Everything has to be necessarily be screamed to anyone, or get isolated."

**Comment by sk22** [comment]
Oh, btw: The distinction between "Unlisted" and "Public" is pretty complicated to wrap one's head around and I think that those options could use some clearer naming. I've created an issue regarding this:  #114

**Comment by retiolus** [comment]
What about adding an "Advanced" category in the settings that would enable this kind of option?

The "Unlisted" option would only appear in the drop-down menu if it is enabled in the advanced settings.

**Comment by FromtonRouge** [comment]
Hello, as a basic user, I don't understand why the "unlisted" option is available on the web client only. I had to install the Tusky app to have this option. It's a Mastodon feature, it should be in the app too

**Comment by MattByName** [comment]
Hi @Gargron , what if the "unlisted" option was not visible by default, but there was a setting to expose it. That way things are simple in the waybyou want, but for users who use unlisted posts due to instance rules or preference can enable it.

I'm thinking of how often the option to hibernate is disabled in windows, but can be enabled in control panel.

**Comment by MattByName** [comment]
Hi @Gargron , what if the "unlisted" option was not visible by default, but there was a setting to expose it. That way things are simple in the waybyou want, but for users who use unlisted posts due to instance rules or preference can enable it.

I'm thinking of how often the option to hibernate is disabled in windows, but can be enabled in control panel.

**Comment by ShadowJonathan** [comment]
@Gargron if you dont agree with this change, simply close the PR, don't let it hang in limbo and become a complaint sinkhole. Stand behind your opinions, if you have them.

**Comment by SamStephens** [comment]
@Gargron 

> This option has been omitted on purpose since it overlaps with public in almost all ways. We keep the dropdown simple, with all other options being very intuitive to understand.

If Unlisted is not intuitive, why is it available in the web application? Are Android users considered to be somehow less capable than web users?

**Comment by MKCOOL142** [comment]
Also currently you could easily fork the feature from other clients based on this  mastodon app, like https://github.com/sk22/megalodon/commit/583325d6e8e03880a8f522814faf34c73756696b

**Comment by SamStephens** [comment]
> Also currently you could easily fork the feature from other clients based on this mastodon app, like [sk22@583325d](https://github.com/sk22/megalodon/commit/583325d6e8e03880a8f522814faf34c73756696b)

Of course I could. I've actually stopped using this client and started using Tusky [now I've been told](https://github.com/mastodon/mastodon-android/issues/22#issuecomment-1321075092):

> This app is for new users. There are more advanced apps for more advanced users.
>  [...]
> This app is for new users. The minimal feature set is purposeful.

But I think that the official Mastodon applications having missing features is bad for the experience users have of Mastodon, and bad for Mastodon's reputation (based on actual comments I've seen from upset users). My take is that either the Mastodon applications should be feature complete, or they should make it clear **to end users** they provide a deliberately limited experience. https://github.com/mastodon/mastodon-android/issues/396 and https://github.com/mastodon/mastodon-ios/issues/698

**Comment by MKCOOL142** [comment]
> @MKCOOL142
> 
> > Also currently you could easily fork the feature from other clients based on this mastodon app, like [sk22@583325d](https://github.com/sk22/megalodon/commit/583325d6e8e03880a8f522814faf34c73756696b)
> 
> Of course I could. I've actually stopped using this client and started using Tusky [now I've been told](https://github.com/mastodon/mastodon-android/issues/22#issuecomment-1321075092):
> 
> > This app is for new users. There are more advanced apps for more advanced users.
> > [...]
> > This app is for new users. The minimal feature set is purposeful.
> 
> But I think that the official Mastodon applications having missing features is bad for the experience users have of Mastodon, and bad for Mastodon's reputation (based on actual comments I've seen from upset users). My take is that either the Mastodon applications should be feature complete, or they should make it clear **to end users** they provide a deliberately limited experience. #396 and [mastodon/mastodon-ios#698](https://github.com/mastodon/mastodon-ios/issues/698)

Yeah I think this app should be Feature complete, and if they don't want to confuse new users than why not have a section in the settings titled "advanced" where all these features for advanced users can get thrown into, with essentially no downsides

**Comment by MKCOOL142** [comment]
> @MKCOOL142
> 
> > Also currently you could easily fork the feature from other clients based on this mastodon app, like [sk22@583325d](https://github.com/sk22/megalodon/commit/583325d6e8e03880a8f522814faf34c73756696b)
> 
> Of course I could. I've actually stopped using this client and started using Tusky [now I've been told](https://github.com/mastodon/mastodon-android/issues/22#issuecomment-1321075092):
> 
> > This app is for new users. There are more advanced apps for more advanced users.
> > [...]
> > This app is for new users. The minimal feature set is purposeful.
> 
> But I think that the official Mastodon applications having missing features is bad for the experience users have of Mastodon, and bad for Mastodon's reputation (based on actual comments I've seen from upset users). My take is that either the Mastodon applications should be feature complete, or they should make it clear **to end users** they provide a deliberately limited experience. #396 and [mastodon/mastodon-ios#698](https://github.com/mastodon/mastodon-ios/issues/698)

Yeah I think this app should be Feature complete, and if they don't want to confuse new users than why not have a section in the settings titled "advanced" where all these features for advanced users can get thrown into, with essentially no downsides

**Comment by jtchen** [comment]
Whether the difference between "unlisted" and "public" toots can be distinguished should be judged by the user, not by the official judgment. If you are worried about novice users, it is reasonable to add an "advanced" switch, and many apps do this.

It is very strange that the features of the official app and the web version of Mastodon are inconsistent. Does this imply that the "unlisted toots" feature of the web version will be removed in the future?

The culture of the instance I am in is, that the public timeline is regarded as a kind of public space, and the administrators will read every article on it. In order to reduce the burden on administrators, many users will use the "unlisted" option to toot. It is because this feature was originally provided, and a corresponding culture was developed. If Mastodon want to turn off this option, you should turn it off completely and officially, so that the culture of the community can be correspondingly changed. Being inconsistent is really unfriendly to users.

**Comment by Lastorder-DC** [comment]
Why this PR is still opened? If this is not going to accepted, just attach `wontfix` label and close.

**Comment by moertel** [comment]
It's so odd to be at the mercy of a single person deciding that an official platform feature should be missing from the official app.

Going silent on the constructive suggestions of balancing UI/UX with an "Advanced Features" toggle is not really encouraging either. People have already invested time in opening a PR, so clearly demonstrated willingness to take on the work.

@Gargron what's a suitable process to continue the discussion? Do you need use cases? Votes? Anything else?

**Comment by shibotto** [comment]
@Gargron please reconsider this. There are instances specifically requiring to post on topic contents only on the public timeline, but allowing whatever else unlisted. This is especially dangerous since Mastodon let's you set the default privacy level for your posts, but this apps also ignores that. It's very easy to not notice it and risk to be banned.

**Comment by Lastorder-DC** [comment]
@Gargron Reconsider, or close this.
It's not that hard. right?

**Comment by YJSoft** [comment]
@Gargron After https://github.com/mastodon/mastodon/pull/26344, all `public` toot of `discoverable` accounts can be searched, unless write as `unlisted`, which is *still* missing from app. Still no plans for merging above? Then, close this.

**Comment by DraconicNEO** [comment]
Does [`f888091`](https://github.com/mastodon/mastodon-android/commit/f888091e22a4f7eff3a48b53b4731bd47ebb45f9) also allow for unlisted in replies, because that's been a big issue ever since they removed the feature, any replies you make in the app are forced public and pollute the timeline.

**Comment by DraconicNEO** [comment]
@grishka Does [`f888091`](https://github.com/mastodon/mastodon-android/commit/f888091e22a4f7eff3a48b53b4731bd47ebb45f9) also allow for unlisted in replies, because that's been a big issue ever since they removed the feature, any replies you make in the app are forced public and pollute the timeline.

**Comment by grishka** [comment]
Yes, the visibility is set to unlisted by default when you reply to an unlisted post.

**Comment by DraconicNEO** [comment]
> Yes, the visibility is set to unlisted by default when you reply to an unlisted post.

I meant any post in general, in most cases it makes sense for replies even to public posts to be unlisted because the original is public and having your replies be public causes them to clutter the timeline, as they appear as posts on the timeline due to being set as public when they probably shouldn't be.

**Pull request closed without merging**
