### PR TITLE
Add line to README saying that the iOS version is not more important than the Android version

### PR DESCRIPTION
**Pull request by upintheairsheep**

### CODE REVIEW

**Comment by upintheairsheep** [comment]
Wow, I get to claim this ID for the rest of eternity.

**Comment by grishka** [comment]
It's unfortunate that this ID is taken by such a PR.

**Comment by upintheairsheep** [comment]
Reopen, there is no reason to close just because the IF

**Comment by grishka** [comment]
We don't do readme PRs.

**Pull request closed without merging**
