### PR TITLE
[BOYSCOUT] some minor findings from static code analysis a-h

### PR DESCRIPTION
**Pull request by winne42**

### CODE REVIEW

**Comment by grishka** [comment]
So did you just run an automated tool to "fix bugs" and submit its result as a pull request? Why would you do that?

**Comment by winne42** [comment]
Hi @grishka , was just browsing the code base and thought I could just as well get rid of some IDE warnings along the way.
Is there some place where I could read about the coding guidelines of the project? 

And, as you are here, maybe you could point me to where I can find `me.grishka.appkit:appkit:1.2.7`? The latest published version on Maven Central seems to be 1.2.6?

Thanks a lot and have a nice weekend!

**Comment by grishka** [comment]
Yes, it's not published yet because I'm not yet sure it's ready. You have to clone the appkit repo and build the library and install it into your local maven repository (`:publishToMavenLocal` gradle task).

**Comment by winne42** [comment]
Great, thanks for the quick feedback, @grishka !

**Comment by tonytamsf** [comment]
FYI: @winne42 I'm starting to learn about the `mastodon-android` repo and I had to add the following to be able to run `./gradlew publishToMavenLocal`

```
diff --git a/appkit/build.gradle b/appkit/build.gradle
index 18d0381..884b435 100755
--- a/appkit/build.gradle
+++ b/appkit/build.gradle
@@ -23,4 +23,11 @@ dependencies {
        implementation 'me.grishka.litex:collection:1.1.0'
 }

-version = '1.2.7'
\ No newline at end of file
+
+signing {
+    setRequired {
+        // signing is only required if the artifacts are to be published
+        gradle.taskGraph.allTasks.any { it.equals( PublishToMavenRepository) }
+    }
+}
+version = '1.2.7'
```

**Pull request closed without merging**
