### PR TITLE
fix: Allow login for limited federation instances

### PR DESCRIPTION
**Pull request by kescherCode**
Addresses #637

### CODE REVIEW

**Comment by kescherCode** [comment]
Still needs further fixes, such as "not crashing when trying to view instance info and rules while logged in"

**Comment by grishka** [comment]
So you're finding an existing session for that instance, and then making a request under that session? That won't address the most popular case when you don't have any sessions on that instance to begin with.

**Comment by kescherCode** [comment]
Check https://cts.kescher.at/about to see why this isn't possible.

You can't see any info about an instance while not logged in. Since there will be an error anyway, "about the instance" can only ever be viewed while logged in to begin with.

**Comment by kescherCode** [comment]
(previous force push was merely an indentation fix)

**Comment by kescherCode** [comment]
See also:

https://github.com/mastodon/mastodon/blob/f92d8c654df654538096efff05e9b1a989d01490/app/controllers/api/v1/instances_controller.rb#L4

https://github.com/mastodon/mastodon/blob/f92d8c654df654538096efff05e9b1a989d01490/app/controllers/api/v1/custom_emojis_controller.rb#L4

**Comment by grishka** [comment]
Still, how do you get that first session going? How common is it to have multiple accounts on the same server?

**Comment by kescherCode** [comment]
The first session, you get going by logging in. That's what the first commit in this PR fixes. The second commit are fixes that *only* apply after logging in.

It doesn't matter how common multiple accounts on the same instance are, does it? I certainly do have that use-case, however.

If you're wondering why I'm just picking any account with a given domain: That's because picking the actual account it would apply to is pretty hard. If you want to, I could force the current account ID to be passed into all methods requiring it.

**Comment by grishka** [comment]
Sorry, I didn't notice the part where it shows a confirmation alert.

**Pull request closed without merging**
