### PR TITLE
Remove M3AlertDialogBuilder class

### PR DESCRIPTION
**Pull request by antmonteiro**
To improve consistency of the app and reduce the unnecessary complexity of the source code remove this class.

If we want to use M3 style we would want to have consistency across the app which means using directly M3 library from google.

Signed-off-by: António Monteiro <antonio.fmr.monteiro@gmail.com>

### CODE REVIEW

**Comment by grishka** [comment]
This isn't helpful.

**Comment by antmonteiro** [comment]
How so?

**Comment by grishka** [comment]
Deleting files in someone else's project to "reduce code complexity" is not helpful.

**Comment by antmonteiro** [comment]
If you think that then I will go ahead and close #330.

**Pull request closed without merging**
