### PR TITLE
Fastlane - update screenshots

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by grishka** [comment]
I don't know where did you get these but they're small. I'll add the original ones.

**Comment by licaon-kter** [comment]
From Play of course :) and yes better put the originals, using the exact same names please.

**Comment by licaon-kter** [comment]
Any news?

**Comment by licaon-kter** [comment]
Any blockers?

**Comment by grishka** [comment]
I don't have original-quality screenshots and people who do ignore me asking for them.

**Comment by licaon-kter** [comment]
An we can't use these in the mean time? I mean these are good enough for Play users... surely they're good enough for F-Droid lol

**Comment by grishka** [comment]
Because I'm a perfectionist :P

I asked for the original ones once again.

**Comment by licaon-kter** [comment]
_Perfect is the enemy of good_

> 
/PS: if that was true we would still have repro builds in F-Droid but alas

**Pull request closed without merging**
