### PR TITLE
fix: UI/UX- Hide compose FAB when in About tab / editing #183

### PR DESCRIPTION
**Pull request by 07prakash**
fixed - #183

https://github.com/mastodon/mastodon-android/assets/135522803/c47aa5b7-7221-4ded-b796-64067afebb3b

### CODE REVIEW

**Comment by 07prakash** [comment]
Hi, review  this

**Comment by grishka** [comment]
Could you please not be so insistent? I'm currently busy with a feature that touches many files. I'll merge this when I'm done with it.

**Comment by 07prakash** [comment]
I'M really SORRY, This is my first contribution. That's why I'm excited

**Comment by grishka** [comment]
I looked at it and I don't like your implementation because you're calling `findViewById` a second time for the same view and also the button will stay hidden if the request to get the profile "source" fails.

**Pull request closed without merging**
